var termina = true;
console.log(termina);
var numEntero = 23;
var numDecimal = 19.45;
var numHex = 0xff00d;
var numBin = 21;
console.log(numHex);
var nombre = "pepe";
var cadena = "Hola me llamo";
console.log(nombre);
